#!/usr/bin/env python

import utils
import sys

words = utils.split_greek_phrase_at_word_boundaries(' '.join(sys.argv[1:]))
for word in words:
    print(utils.lookup_word(word))


  # for example: ./lookup "ἐν ἀρχῇ ἦν ὁ λόγος" | jq .
